version: "3.7"
services:
  frontend:
    build: ./Frontend
    ports:
      - "4173:4173"

  backend:
    build: ./Backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
      - CLOUDINARY_CLOUD_NAME=${CLOUD_NAME}
      - CLOUDINARY_API_KEY=${API_KEY}
      - CLOUDINARY_API_SECRET=${API_SECRET}
    env_file:
      - .env
    