version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
      - CLOUDINARY_CLOUD_NAME=${CLOUD_NAME}
      - CLOUDINARY_API_KEY=${API_KEY}
      - CLOUDINARY_API_SECRET=${API_SECRET}
    env_file:
      - .env
    